# Generated by Django 3.2.3 on 2021-05-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('text', models.TextField(blank=True, null=True)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('task_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('text', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('report_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
                ('manager_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
            ],
        ),
    ]
