# Generated by Django 3.2.3 on 2021-05-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210526_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
    ]
