# Generated by Django 3.2.3 on 2021-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
