# Generated by Django 3.2.3 on 2021-05-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
    ]
